### ISSUE TITLE
Teclado tampando textfields na tela de login

### ISSUE THREAD

**Issue by matheusc3m** [flavioccf/lacrei-flutter#1]
Quando clica no textfield o teclado fica por cima ai não dá pra descer a tela, olhei muito pouco, mas adicionando um scroll resolveria esse problema, talvez um singlechildscrollview ou modificando o seu scroll

**Comment by flavioccf** [comment]
Ajustado... o código da página estava OK, havia alguma incompatibilidade com o splash screen, eu removi e alterei para um plugin [.](https://pub.dev/packages/animated_splash) agora está OK novamente.
